
[window]
# Window settings
padding = { x = 10, y = 10 }
dynamic_title = true
startup_mode = "Maximized"
blur = true

[font]
# Font configuration
normal = { family = "NotoSansM Nerd Font Propo", style = "Bold" }
bold = { family = "NotoSansM Nerd Font Propo", style = "Bold" }
italic = { family = "NotoSansM Nerd Font Propo", style = "Italic" }
size = 15

[keyboard]
bindings = [{ key = "Space", mods = "Control", chars = "\u0000" }]


[colors.cursor]
text = '0x1E1E1E'
cursor = '0x528BFF'

[colors.selection]
text = '0xFFFFFF'
background = '0x264F78'

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = "Block"
blink_interval = 500

[terminal.shell]
program = "wsl ~"

[env]
ALACRITTY_ENV = "true"
WSLENV = "ALACRITTY_ENV/u"

[general]
# Configuration for Alacritty, the GPU enhanced terminal emulator
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[terminal]
